"""
Sandbox utilities package.

Python port of src/utils/sandbox/.
"""

from .sandbox_adapter import (
    SandboxDependencyCheck,
    SandboxRuntimeConfig,
    SandboxRuntimeFilesystemConfig,
    SandboxRuntimeNetworkConfig,
    SandboxSettings,
    SandboxViolationEvent,
    are_sandbox_settings_locked_by_policy,
    are_unsandboxed_commands_allowed,
    check_dependencies,
    cleanup_after_command,
    convert_to_sandbox_runtime_config,
    extract_sandbox_settings,
    get_excluded_commands,
    get_linux_glob_pattern_warnings,
    get_platform,
    get_sandbox_enabled_setting,
    get_sandbox_unavailable_reason,
    get_sandbox_violation_store,
    initialize,
    is_auto_allow_bash_if_sandboxed_enabled,
    is_command_allowed,
    is_command_sandboxed,
    is_platform_in_enabled_list,
    is_sandbox_required,
    is_sandboxing_enabled,
    is_supported_platform,
    refresh_config,
    reset,
    resolve_path_pattern_for_sandbox,
    resolve_sandbox_filesystem_path,
    should_allow_managed_sandbox_domains_only,
    should_use_sandbox,
    wrap_with_sandbox,
)
from .sandbox_ui_utils import remove_sandbox_violation_tags

__all__ = [
    "SandboxDependencyCheck",
    "SandboxRuntimeConfig",
    "SandboxRuntimeFilesystemConfig",
    "SandboxRuntimeNetworkConfig",
    "SandboxSettings",
    "SandboxViolationEvent",
    "are_sandbox_settings_locked_by_policy",
    "are_unsandboxed_commands_allowed",
    "check_dependencies",
    "cleanup_after_command",
    "convert_to_sandbox_runtime_config",
    "extract_sandbox_settings",
    "get_excluded_commands",
    "get_linux_glob_pattern_warnings",
    "get_platform",
    "get_sandbox_enabled_setting",
    "get_sandbox_unavailable_reason",
    "get_sandbox_violation_store",
    "initialize",
    "is_auto_allow_bash_if_sandboxed_enabled",
    "is_command_allowed",
    "is_command_sandboxed",
    "is_platform_in_enabled_list",
    "is_sandbox_required",
    "is_sandboxing_enabled",
    "is_supported_platform",
    "refresh_config",
    "remove_sandbox_violation_tags",
    "reset",
    "resolve_path_pattern_for_sandbox",
    "resolve_sandbox_filesystem_path",
    "should_allow_managed_sandbox_domains_only",
    "should_use_sandbox",
    "wrap_with_sandbox",
]
