package com.l2dchat.core.mem

import org.junit.Assert.assertEquals
import org.junit.Assert.assertTrue
import org.junit.Test

/**
 * Cross-validated against Python `mem/lexical.tokenize` and
 * `mem/lexical.BM25Index` (file `/home/tcmofashi/proj/t_memorix/src/mem/lexical.py`,
 * 137 lines).
 *
 * Every token list and BM25 score below was generated by actually running the
 * Python reference with `python3` and pasted here verbatim — never mentally
 * computed. The generator was:
 *
 * ```python
 * import sys
 * sys.path.insert(0, "/home/tcmofashi/proj/t_memorix/src")
 * from mem.lexical import tokenize, BM25Index
 * ```
 *
 * JDK `java.text.Normalizer.Form.NFKC` and Python `unicodedata.normalize("NFKC")`
 * implement the same versioned Unicode normalization algorithm, so token lists
 * are expected to be byte-identical for every input exercised here.
 */
class BM25IndexTest {

    // ------------------------------------------------------------------
    // isCjk — boundary coverage of the three Unicode ranges from lexical.py.
    // ------------------------------------------------------------------

    @Test
    fun `isCjk returns false for code points just below each range`() {
        // U+4DFF, U+33FF, U+F8FF — last excluded code point of each range.
        assertEquals(false, isCjk(0x4DFF.toChar()))
        assertEquals(false, isCjk(0x33FF.toChar()))
        assertEquals(false, isCjk(0xF8FF.toChar()))
    }

    @Test
    fun `isCjk returns true at the inclusive bounds of each range`() {
        // U+4E00, U+9FFF, U+3400, U+4DBF, U+F900, U+FAFF.
        assertEquals(true, isCjk(0x4E00.toChar()))
        assertEquals(true, isCjk(0x9FFF.toChar()))
        assertEquals(true, isCjk(0x3400.toChar()))
        assertEquals(true, isCjk(0x4DBF.toChar()))
        assertEquals(true, isCjk(0xF900.toChar()))
        assertEquals(true, isCjk(0xFAFF.toChar()))
    }

    @Test
    fun `isCjk returns false for code points just above each range`() {
        // U+A000, U+4DC0, U+FB00 — first excluded code point of each range.
        assertEquals(false, isCjk(0xA000.toChar()))
        assertEquals(false, isCjk(0x4DC0.toChar()))
        assertEquals(false, isCjk(0xFB00.toChar()))
    }

    @Test
    fun `isCjk returns false for ASCII letters and digits`() {
        for (ch in "KFC log qwen3 0123") {
            assertEquals(false, isCjk(ch))
        }
    }

    // ------------------------------------------------------------------
    // tokenize — exact list equality against Python outputs.
    //
    // NOTE: emission order is interleaved (unigram, then bigram with the
    // previous CJK char) as each CJK char is scanned. Do NOT assume all
    // unigrams precede all bigrams; the order below mirrors Python exactly.
    // ------------------------------------------------------------------

    @Test
    fun `tokenize of 罗联政府 emits interleaved unigrams and bigrams matching Python`() {
        // Python: tokenize("罗联政府")
        assertEquals(
            listOf("罗", "联", "罗联", "政", "联政", "府", "政府"),
            tokenize("罗联政府"),
        )
    }

    @Test
    fun `tokenize of KFC log lowercases and splits on whitespace matching Python`() {
        // Python: tokenize("KFC log")
        assertEquals(listOf("kfc", "log"), tokenize("KFC log"))
    }

    @Test
    fun `tokenize folds fullwidth ＫＦＣ to kfc matching Python`() {
        // Python: tokenize("ＫＦＣ")  ->  ["kfc"]
        assertEquals(listOf("kfc"), tokenize("ＫＦＣ"))
    }

    @Test
    fun `tokenize of mixed CJK and latin 罗联KFC政府 matching Python`() {
        // Python: tokenize("罗联KFC政府")
        assertEquals(
            listOf("罗", "联", "罗联", "kfc", "政", "府", "政府"),
            tokenize("罗联KFC政府"),
        )
    }

    @Test
    fun `tokenize of 用户养了一只猫 matching Python`() {
        // Python: tokenize("用户养了一只猫")
        assertEquals(
            listOf(
                "用", "户", "用户",
                "养", "户养",
                "了", "养了",
                "一", "了一",
                "只", "一只",
                "猫", "只猫",
            ),
            tokenize("用户养了一只猫"),
        )
    }

    @Test
    fun `tokenize treats CJK punctuation as separator matching Python`() {
        // Python: tokenize("罗联政府，KFC开业了！")
        assertEquals(
            listOf(
                "罗", "联", "罗联", "政", "联政", "府", "政府",
                "kfc",
                "开", "业", "开业", "了", "业了",
            ),
            tokenize("罗联政府，KFC开业了！"),
        )
    }

    @Test
    fun `tokenize of empty string returns empty list matching Python`() {
        assertEquals(emptyList<String>(), tokenize(""))
    }

    @Test
    fun `tokenize of whitespace-only string returns empty list matching Python`() {
        assertEquals(emptyList<String>(), tokenize("  "))
    }

    @Test
    fun `tokenize keeps latin-digit runs whole matching Python`() {
        // Python: tokenize("qwen3")  ->  ["qwen3"]
        assertEquals(listOf("qwen3"), tokenize("qwen3"))
    }

    @Test
    fun `tokenize splits Hello World on punctuation matching Python`() {
        // Python: tokenize("Hello, World!")  ->  ["hello", "world"]
        assertEquals(listOf("hello", "world"), tokenize("Hello, World!"))
    }

    @Test
    fun `tokenize folds fullwidth alnum ＡＢＣ１２３ to abc123 matching Python`() {
        // Python: tokenize("ＡＢＣ１２３")  ->  ["abc123"]
        assertEquals(listOf("abc123"), tokenize("ＡＢＣ１２３"))
    }

    // ------------------------------------------------------------------
    // BM25Index — ranking, discard, re-add, empty handling, tie-break.
    // Scores are Python reference values pasted verbatim.
    // ------------------------------------------------------------------

    @Test
    fun `size reports the number of indexed documents`() {
        val idx = BM25Index()
        assertEquals(0, idx.size())
        idx.add("d1", "罗联政府")
        assertEquals(1, idx.size())
        idx.add("d2", "罗联")
        assertEquals(2, idx.size())
        idx.discard("d1")
        assertEquals(1, idx.size())
    }

    @Test
    fun `search ranks documents by BM25 score descending matching Python`() {
        val idx = BM25Index()
        idx.add("d1", "罗联政府")
        idx.add("d2", "罗联")
        idx.add("d3", "KFC开业")

        // Python: idx.search("罗联", 5)
        //   d2: 1.680012972623055
        //   d1: 1.1510292961120057
        val result = idx.search("罗联", 5)
        assertEquals(listOf("d2", "d1"), result.map { it.first })
        assertEquals(1.680012972623055, result[0].second, 1e-12)
        assertEquals(1.1510292961120057, result[1].second, 1e-12)
    }

    @Test
    fun `search with multi-term query accumulates scores matching Python`() {
        val idx = BM25Index()
        idx.add("d1", "罗联政府")
        idx.add("d2", "罗联")
        idx.add("d3", "KFC开业")

        // Python: idx.search("罗联政府", 5)
        //   d1: 4.353737061048255
        //   d2: 1.680012972623055
        val result = idx.search("罗联政府", 5)
        assertEquals(listOf("d1", "d2"), result.map { it.first })
        assertEquals(4.353737061048255, result[0].second, 1e-12)
        assertEquals(1.680012972623055, result[1].second, 1e-12)
    }

    @Test
    fun `search is case-insensitive after NFKC and lowercase`() {
        val idx = BM25Index()
        idx.add("d3", "KFC开业")
        // Python: idx.search("KFC", 5) == idx.search("kfc", 5)
        assertEquals(idx.search("KFC", 5), idx.search("kfc", 5))
        // Python: idx.search("KFC", 5)  ->  d3: 0.28768207245178085
        // (1-doc index → lower IDF than the 3-doc index score 1.048…)
        val result = idx.search("KFC", 5)
        assertEquals(listOf("d3"), result.map { it.first })
        assertEquals(0.28768207245178085, result[0].second, 1e-12)
    }

    @Test
    fun `search with combined CJK and latin query ranks all matching docs matching Python`() {
        val idx = BM25Index()
        idx.add("d1", "罗联政府")
        idx.add("d2", "罗联")
        idx.add("d3", "KFC开业")

        // Python: idx.search("罗联 KFC", 5)
        //   d2: 1.680012972623055
        //   d1: 1.1510292961120057
        //   d3: 1.0482144688674937
        val result = idx.search("罗联 KFC", 5)
        assertEquals(listOf("d2", "d1", "d3"), result.map { it.first })
        assertEquals(1.680012972623055, result[0].second, 1e-12)
        assertEquals(1.1510292961120057, result[1].second, 1e-12)
        assertEquals(1.0482144688674937, result[2].second, 1e-12)
    }

    @Test
    fun `search on tiny corpus matches hand-computable Python scores`() {
        val idx = BM25Index()
        idx.add("a", "cat")
        idx.add("b", "cat cat")
        idx.add("c", "dog")

        // Python: idx.search("cat", 5)
        //   b: 0.5784660052255207
        //   a: 0.5295815540797021
        val cat = idx.search("cat", 5)
        assertEquals(listOf("b", "a"), cat.map { it.first })
        assertEquals(0.5784660052255207, cat[0].second, 1e-12)
        assertEquals(0.5295815540797021, cat[1].second, 1e-12)

        // Python: idx.search("dog", 5)
        //   c: 1.1051597217033537
        val dog = idx.search("dog", 5)
        assertEquals(listOf("c"), dog.map { it.first })
        assertEquals(1.1051597217033537, dog[0].second, 1e-12)
    }

    @Test
    fun `search with empty query returns empty list`() {
        val idx = BM25Index()
        idx.add("d1", "罗联政府")
        assertEquals(emptyList<Pair<String, Double>>(), idx.search("", 5))
    }

    @Test
    fun `search on empty index returns empty list`() {
        val idx = BM25Index()
        assertEquals(emptyList<Pair<String, Double>>(), idx.search("anything", 5))
    }

    @Test
    fun `search with non-positive k returns empty list`() {
        val idx = BM25Index()
        idx.add("d1", "罗联政府")
        assertEquals(emptyList<Pair<String, Double>>(), idx.search("罗联", 0))
        assertEquals(emptyList<Pair<String, Double>>(), idx.search("罗联", -1))
    }

    @Test
    fun `search with k larger than result set returns all matches`() {
        val idx = BM25Index()
        idx.add("d1", "罗联政府")
        idx.add("d2", "罗联")
        // Only two docs match; k=10 must still return exactly two.
        val result = idx.search("罗联", 10)
        assertEquals(2, result.size)
    }

    @Test
    fun `search with no matching terms returns empty list`() {
        val idx = BM25Index()
        idx.add("d1", "罗联政府")
        assertEquals(emptyList<Pair<String, Double>>(), idx.search("完全不匹配的词", 5))
    }

    @Test
    fun `discard removes the document from search results`() {
        val idx = BM25Index()
        idx.add("x1", "alpha")
        idx.add("x2", "alpha beta")

        // Python before discard:
        //   x1: 0.21449594916935832
        //   x2: 0.15854048416865615
        val before = idx.search("alpha", 5)
        assertEquals(listOf("x1", "x2"), before.map { it.first })
        assertEquals(0.21449594916935832, before[0].second, 1e-12)
        assertEquals(0.15854048416865615, before[1].second, 1e-12)

        idx.discard("x1")
        assertEquals(1, idx.size())

        // Python after discard x1:
        //   x2: 0.28768207245178085
        val after = idx.search("alpha", 5)
        assertEquals(listOf("x2"), after.map { it.first })
        assertEquals(0.28768207245178085, after[0].second, 1e-12)
    }

    @Test
    fun `discard of unknown id is a no-op`() {
        val idx = BM25Index()
        idx.add("d1", "alpha")
        idx.discard("does-not-exist")
        assertEquals(1, idx.size())
        assertEquals(listOf("d1"), idx.search("alpha", 5).map { it.first })
    }

    @Test
    fun `add of existing id replaces the previous posting`() {
        val idx = BM25Index()
        idx.add("r1", "alpha")
        idx.add("r1", "beta")
        // Python: size == 1, search("alpha") == [], search("beta") == [("r1", 0.28768207245178085)]
        assertEquals(1, idx.size())
        assertEquals(emptyList<Pair<String, Double>>(), idx.search("alpha", 5))
        val beta = idx.search("beta", 5)
        assertEquals(listOf("r1"), beta.map { it.first })
        assertEquals(0.28768207245178085, beta[0].second, 1e-12)
    }

    @Test
    fun `add of empty or separator-only text is ignored`() {
        val idx = BM25Index()
        idx.add("e1", "")
        idx.add("e2", "!!!")
        idx.add("e3", "real content")
        // Python: size == 1 (only e3 stored)
        assertEquals(1, idx.size())
        val result = idx.search("content", 5)
        // Python: idx.search("content", 5)  ->  e3: 0.28768207245178085
        assertEquals(listOf("e3"), result.map { it.first })
        assertEquals(0.28768207245178085, result[0].second, 1e-12)
    }

    @Test
    fun `search tie-breaks equal scores by doc id ascending`() {
        val idx = BM25Index()
        idx.add("zzz", "same")
        idx.add("aaa", "same")
        idx.add("mmm", "same")
        // Python: idx.search("same", 3)
        //   aaa: 0.13353139262452257
        //   mmm: 0.13353139262452257
        //   zzz: 0.13353139262452257
        val result = idx.search("same", 3)
        assertEquals(listOf("aaa", "mmm", "zzz"), result.map { it.first })
        // All three scores identical.
        assertEquals(0.13353139262452257, result[0].second, 1e-12)
        assertEquals(0.13353139262452257, result[1].second, 1e-12)
        assertEquals(0.13353139262452257, result[2].second, 1e-12)
    }

    @Test
    fun `search is deterministic across repeated calls`() {
        val idx = BM25Index()
        idx.add("d1", "罗联政府")
        idx.add("d2", "罗联")
        idx.add("d3", "KFC开业")
        val first = idx.search("罗联 KFC", 5)
        val second = idx.search("罗联 KFC", 5)
        val third = idx.search("罗联 KFC", 5)
        assertEquals(first, second)
        assertEquals(second, third)
    }

    @Test
    fun `custom k1 and b parameters are accepted`() {
        // Smoke test: non-default params must not throw and must still rank
        // the matching document first. Exact scores for non-default params are
        // not cross-validated here; the default-param tests cover score parity.
        val idx = BM25Index(k1 = 1.2, b = 0.5)
        idx.add("a", "cat")
        idx.add("b", "cat cat")
        val result = idx.search("cat", 5)
        assertEquals(listOf("b", "a"), result.map { it.first })
        assertTrue("top score must be positive", result[0].second > 0.0)
    }
}
