package com.l2dchat.core.mem

import org.junit.Assert.assertEquals
import org.junit.Assert.assertNotEquals
import org.junit.Assert.assertTrue
import org.junit.Assert.fail
import org.junit.Test

/**
 * Cross-validated against Python `mem/hashing.short_hash`.
 *
 * Reference values were generated by:
 *
 * ```python
 * import base64, hashlib
 * def short_hash(text, length=12):
 *     digest = hashlib.sha256(text.encode("utf-8")).digest()
 *     return base64.urlsafe_b64encode(digest).decode("ascii").rstrip("=")[:length]
 * ```
 *
 * Hashes MUST be byte-identical with the Python implementation so that content
 * addressing stays stable across the port.
 */
class HashingTest {
    @Test
    fun `shortHash is deterministic for identical inputs`() {
        val a = Hashing.shortHash("test", 12)
        val b = Hashing.shortHash("test", 12)
        val c = Hashing.shortHash("test", 12)
        assertEquals(a, b)
        assertEquals(b, c)
        assertEquals("n4bQgYhMfWWa", a)
    }

    @Test
    fun `shortHash of test matches Python reference`() {
        assertEquals("n4bQgYhMfWWa", Hashing.shortHash("test"))
    }

    @Test
    fun `shortHash of mixed CJK and ASCII matches Python reference`() {
        // Reference (length=12): 'fOJD6hJ6U_Ng'
        assertEquals(
            "fOJD6hJ6U_Ng",
            Hashing.shortHash("event用户提到了项目X2026-08-08"),
        )
    }

    @Test
    fun `shortHash of pure CJK text matches Python reference`() {
        // Reference (length=12): '_6DT87FBmogF'
        assertEquals("_6DT87FBmogF", Hashing.shortHash("婚礼改到下周六了"))
    }

    @Test
    fun `shortHash of long English sentence matches Python reference`() {
        // Reference (length=12): 'aEV3ssY-PnkH'
        val text =
                "The quick brown fox jumps over the lazy dog repeatedly and then sits " +
                        "down for a while before the next adventure begins in the open field " +
                        "under the bright blue sky."
        assertEquals("aEV3ssY-PnkH", Hashing.shortHash(text))
    }

    @Test
    fun `shortHash of empty string does not throw and matches Python reference`() {
        // Reference (length=12): '47DEQpj8HBSa'
        val result = Hashing.shortHash("")
        assertEquals("47DEQpj8HBSa", result)
    }

    @Test
    fun `shortHash default length is 12`() {
        // Reference (length=12): 'fOJD6hJ6U_Ng'
        val explicit = Hashing.shortHash("event用户提到了项目X2026-08-08", 12)
        val defaulted = Hashing.shortHash("event用户提到了项目X2026-08-08")
        assertEquals(explicit, defaulted)
        assertEquals(12, defaulted.length)
    }

    @Test
    fun `shortHash with length 8 returns exactly 8 chars matching Python reference`() {
        assertEquals("n4bQgYhM", Hashing.shortHash("test", 8))
        assertEquals("fOJD6hJ6", Hashing.shortHash("event用户提到了项目X2026-08-08", 8))
        assertEquals("47DEQpj8", Hashing.shortHash("", 8))
        assertEquals("_6DT87FB", Hashing.shortHash("婚礼改到下周六了", 8))
        assertEquals(
            "aEV3ssY-",
            Hashing.shortHash(
                "The quick brown fox jumps over the lazy dog repeatedly and then sits " +
                        "down for a while before the next adventure begins in the open field " +
                        "under the bright blue sky.",
                8,
            ),
        )
    }

    @Test
    fun `shortHash with length 0 returns empty string without throwing`() {
        assertEquals("", Hashing.shortHash("anything", 0))
        assertEquals("", Hashing.shortHash("", 0))
    }

    @Test
    fun `shortHash with length greater than base64 width returns full base64 without padding`() {
        // SHA-256 digest is 32 bytes → 43 base64 chars after padding stripped.
        // Reference (length=43): 'n4bQgYhMfWWaL-qgxVrQFaO_TxsrC4Is0V1sFbDwCgg'
        assertEquals(
            "n4bQgYhMfWWaL-qgxVrQFaO_TxsrC4Is0V1sFbDwCgg",
            Hashing.shortHash("test", 43),
        )
        // Length well beyond digest width is capped at the actual base64 length.
        assertEquals(
            43,
            Hashing.shortHash("test", 1000).length,
        )
    }

    @Test
    fun `shortHash outputs are URL-safe base64 characters only`() {
        val samples = listOf(
            "test",
            "event用户提到了项目X2026-08-08",
            "",
            "婚礼改到下周六了",
            "ascii only content with + and / tricky chars",
        )
        for (sample in samples) {
            val hash = Hashing.shortHash(sample, 43)
            assertTrue(
                "Hash must be URL-safe (no '+', '/', or '='): got '$hash'",
                hash.all { it.isLetterOrDigit() || it == '-' || it == '_' },
            )
            assertTrue(
                "Hash must not contain Base64 padding: got '$hash'",
                '=' !in hash,
            )
        }
    }

    @Test
    fun `shortHash produces different outputs for different inputs`() {
        val a = Hashing.shortHash("alpha")
        val b = Hashing.shortHash("beta")
        assertNotEquals(a, b)
    }

    @Test
    fun `shortHash is sensitive to every byte of input`() {
        // Single character difference must change the hash.
        val original = Hashing.shortHash("test")
        val mutated = Hashing.shortHash("tes")
        assertNotEquals(original, mutated)
    }

    @Test
    fun `shortHash with negative length throws IllegalArgumentException`() {
        try {
            Hashing.shortHash("test", -1)
            fail("Expected IllegalArgumentException for negative length")
        } catch (e: IllegalArgumentException) {
            assertTrue(
                "Exception message must mention 'length': ${e.message}",
                e.message?.contains("length") == true,
            )
        }
    }
}
