package com.l2dchat.core.mem

import java.time.ZoneId
import org.junit.Assert.assertEquals
import org.junit.Assert.assertFalse
import org.junit.Assert.assertNotEquals
import org.junit.Assert.assertNull
import org.junit.Assert.assertTrue
import org.junit.Test

/**
 * Cross-validated unit tests for [Operators] — Kotlin port of `mem/operators.py`.
 *
 * Every numeric assertion below was generated by running the Python reference
 * `mem/operators.py` (overlap / rank / present) under `TZ=Asia/Shanghai` and
 * recording the exact output. The Kotlin side passes [ZoneId.of]`("Asia/Shanghai")`
 * explicitly to [Operators.present] so the suite is timezone-independent and
 * reproduces the Python output bit-for-bit.
 *
 * Reference generation command (run 2026-08-13 against `t_memorix` HEAD):
 * ```
 * TZ=Asia/Shanghai python3 -c "import sys; sys.path.insert(0,'src'); \
 *   from mem.operators import rank, present; ..."
 * ```
 *
 * Rank tolerance: Python floats are IEEE-754 doubles; Kotlin Doubles are the
 * same width, so the values match to within `1e-9` after the usual
 * associativity/ordering wobble.
 */
class OperatorsTest {

    private val zone = ZoneId.of("Asia/Shanghai")

    // ------------------------------------------------------------------
    // Constants
    // ------------------------------------------------------------------

    @Test
    fun `constants match the Python reference exactly`() {
        // Python: SECONDS_PER_DAY == 86400.0, PREVIEW_LENGTH == 80, HASH_PREFIX_LENGTH == 8
        assertEquals(86400.0, Operators.SECONDS_PER_DAY, 0.0)
        assertEquals(80, Operators.PREVIEW_LENGTH)
        assertEquals(8, Operators.HASH_PREFIX_LENGTH)
    }

    // ------------------------------------------------------------------
    // overlap — Python: a_start < b_end and b_start < a_end
    // ------------------------------------------------------------------

    @Test
    fun `overlap returns false for disjoint touching intervals`() {
        // Python: overlap(1.0, 2.0, 2.0, 3.0) == False
        assertFalse(Operators.overlap(1L, 2L, 2L, 3L))
    }

    @Test
    fun `overlap returns false for disjoint intervals with gap`() {
        // Python: overlap(1.0, 2.0, 5.0, 6.0) == False
        assertFalse(Operators.overlap(1L, 2L, 5L, 6L))
    }

    @Test
    fun `overlap returns true for partial overlap`() {
        // Python: overlap(1.0, 3.0, 2.0, 4.0) == True
        assertTrue(Operators.overlap(1L, 3L, 2L, 4L))
    }

    @Test
    fun `overlap returns true when one interval contains the other`() {
        // Python: overlap(1.0, 10.0, 3.0, 5.0) == True
        assertTrue(Operators.overlap(1L, 10L, 3L, 5L))
    }

    @Test
    fun `overlap returns true for identical intervals`() {
        // Python: overlap(1.0, 5.0, 1.0, 5.0) == True
        assertTrue(Operators.overlap(1L, 5L, 1L, 5L))
    }

    @Test
    fun `overlap treats empty interval as a point - disjoint point returns false`() {
        // Python: overlap(2.0, 2.0, 3.0, 5.0) == False
        assertFalse(Operators.overlap(2L, 2L, 3L, 5L))
    }

    @Test
    fun `overlap treats empty interval as a point - point inside returns true`() {
        // Python: overlap(3.0, 3.0, 2.0, 5.0) == True
        assertTrue(Operators.overlap(3L, 3L, 2L, 5L))
    }

    @Test
    fun `overlap treats empty interval at inclusive start as true`() {
        // Python: overlap(2.0, 2.0, 2.0, 5.0) == False  (point at start is excluded
        // by the half-open semantics: b_start=2 < a_end=2 is false).
        assertFalse(Operators.overlap(2L, 2L, 2L, 5L))
    }

    @Test
    fun `overlap treats empty interval at exclusive end as false`() {
        // Python: overlap(5.0, 5.0, 2.0, 5.0) == False
        assertFalse(Operators.overlap(5L, 5L, 2L, 5L))
    }

    @Test
    fun `overlap of two zero-length intervals at the same point is false`() {
        // Python: overlap(3.0, 3.0, 3.0, 3.0) == False
        // Both [3,3) are empty half-open intervals; they share no point.
        assertFalse(Operators.overlap(3L, 3L, 3L, 3L))
    }

    @Test
    fun `overlap returns false when first interval is reversed`() {
        // Python: overlap(5.0, 1.0, 2.0, 3.0) == False
        assertFalse(Operators.overlap(5L, 1L, 2L, 3L))
    }

    @Test
    fun `overlap returns false when second interval is reversed`() {
        // Python: overlap(1.0, 2.0, 5.0, 3.0) == False
        assertFalse(Operators.overlap(1L, 2L, 5L, 3L))
    }

    // ------------------------------------------------------------------
    // rank — Python: score * decay/boost * (1 + 0.05*log1p(entity_weight))
    // ------------------------------------------------------------------

    /**
     * Fixed "now" used by every rank case. Matches the Python reference run so
     * the hardcoded `final` values are directly comparable.
     */
    private val now: Long = 1786000000L

    private val day: Long = 86400L

    @Test
    fun `rank applies mention-axis decay for a past event 30 days ago with cosine 0_9`() {
        // Python: rank([{"score":0.9,"mention_time":now-30*day,"start_ts":None,"entity_weight":0}], now)
        //       -> final == 0.9 * 0.95**30 * (1 + 0.05*log1p(0)) == 0.19317488754864354
        val item = RankItem(
            id = "past30",
            score = 0.9,
            mentionTime = now - 30 * day,
            startTs = null,
            entityWeight = 0L,
        )
        val scored = Operators.rank(listOf(item), now)
        assertEquals(0.19317488754864354, scored[0].finalScore, 1e-9)
    }

    @Test
    fun `rank applies proximity boost for a future event 7 days away with cosine 0_8`() {
        // Python: final == 0.8 * 1/(1 + 7/7) * 1 == 0.4
        val item = RankItem(
            id = "future7",
            score = 0.8,
            mentionTime = now - 1 * day,
            startTs = now + 7 * day,
            entityWeight = 0L,
        )
        val scored = Operators.rank(listOf(item), now)
        assertEquals(0.4, scored[0].finalScore, 1e-9)
    }

    @Test
    fun `rank applies entity weighting for an entity-linked node with count 10 and cosine 0_7`() {
        // Python: final == 0.7 * 0.95**0 * (1 + 0.05*log1p(10)) == 0.7839263345479429
        val item = RankItem(
            id = "entity10",
            score = 0.7,
            mentionTime = now,
            startTs = null,
            entityWeight = 10L,
        )
        val scored = Operators.rank(listOf(item), now)
        assertEquals(0.7839263345479429, scored[0].finalScore, 1e-9)
    }

    @Test
    fun `rank defaults entity weight to zero when the field is missing-equivalent`() {
        // Python: item without "entity_weight" -> final == 0.5 * 0.95**0 * 1 == 0.5
        // RankItem defaults entityWeight to 0, matching Python's `item.get("entity_weight") or 0.0`.
        val item = RankItem(
            id = "no-ew",
            score = 0.5,
            mentionTime = now,
            startTs = null,
        )
        val scored = Operators.rank(listOf(item), now)
        assertEquals(0.5, scored[0].finalScore, 1e-9)
        assertEquals(0L, scored[0].entityWeight)
    }

    @Test
    fun `rank treats start_ts equal to now as not-future and applies decay`() {
        // Python: start_ts == now -> decay branch.
        // final == 0.6 * 0.95**2 * 1 == 0.5415
        val item = RankItem(
            id = "start-eq-now",
            score = 0.6,
            mentionTime = now - 2 * day,
            startTs = now,
            entityWeight = 0L,
        )
        val scored = Operators.rank(listOf(item), now)
        assertEquals(0.5415, scored[0].finalScore, 1e-9)
    }

    @Test
    fun `rank treats past start_ts as already-happened and applies decay`() {
        // Python: start_ts < now -> decay branch (mention_time 5 days ago).
        // final == 0.6 * 0.95**5 * 1 == 0.4642685624999998
        val item = RankItem(
            id = "past-start",
            score = 0.6,
            mentionTime = now - 5 * day,
            startTs = now - 10 * day,
            entityWeight = 0L,
        )
        val scored = Operators.rank(listOf(item), now)
        assertEquals(0.4642685624999998, scored[0].finalScore, 1e-9)
    }

    @Test
    fun `rank one-day decay equals 0_95`() {
        // Python: final == 1.0 * 0.95**1 * 1 == 0.95
        val item = RankItem(
            id = "1day",
            score = 1.0,
            mentionTime = now - day,
            startTs = null,
            entityWeight = 0L,
        )
        val scored = Operators.rank(listOf(item), now)
        assertEquals(0.95, scored[0].finalScore, 1e-9)
    }

    @Test
    fun `rank future one-day boost equals 7 over 8`() {
        // Python: final == 1.0 * 1/(1 + 1/7) * 1 == 0.875
        val item = RankItem(
            id = "future-1d",
            score = 1.0,
            mentionTime = now,
            startTs = now + day,
            entityWeight = 0L,
        )
        val scored = Operators.rank(listOf(item), now)
        assertEquals(0.875, scored[0].finalScore, 1e-9)
    }

    @Test
    fun `rank sorts by final descending and preserves input order for ties`() {
        // Python: rank multi -> ids ['a','c','d','b'], finals [0.5, 0.5, 0.4, 0.19317488754864354]
        // 'a' and 'c' tie at 0.5; stable sort keeps 'a' before 'c'.
        val items = listOf(
            RankItem(id = "a", score = 0.5, mentionTime = now, startTs = null, entityWeight = 0L),
            RankItem(id = "b", score = 0.9, mentionTime = now - 30 * day, startTs = null, entityWeight = 0L),
            RankItem(id = "c", score = 0.5, mentionTime = now, startTs = null, entityWeight = 0L),
            RankItem(
                id = "d",
                score = 0.8,
                mentionTime = now - day,
                startTs = now + 7 * day,
                entityWeight = 0L,
            ),
        )
        val scored = Operators.rank(items, now)
        assertEquals(listOf("a", "c", "d", "b"), scored.map { it.id })
        assertEquals(0.5, scored[0].finalScore, 1e-9)
        assertEquals(0.5, scored[1].finalScore, 1e-9)
        assertEquals(0.4, scored[2].finalScore, 1e-9)
        assertEquals(0.19317488754864354, scored[3].finalScore, 1e-9)
    }

    @Test
    fun `rank does not mutate the input items finalScore`() {
        // Python: `final` is only added to the copied rows; the input dicts are untouched.
        val item = RankItem(
            id = "x",
            score = 0.9,
            mentionTime = now - 30 * day,
            startTs = null,
            entityWeight = 0L,
        )
        Operators.rank(listOf(item), now)
        assertEquals(0.0, item.finalScore, 0.0)
    }

    @Test
    fun `rank returns a new list leaving the input collection unchanged`() {
        val original = listOf(
            RankItem(id = "a", score = 0.5, mentionTime = now, startTs = null),
            RankItem(id = "b", score = 0.9, mentionTime = now - 30 * day, startTs = null),
        )
        val scored = Operators.rank(original, now)
        // The input list still has its original order and no final set.
        assertEquals(listOf("a", "b"), original.map { it.id })
        original.forEach { assertEquals(0.0, it.finalScore, 0.0) }
        // The output is sorted and has finals.
        assertEquals(listOf("a", "b"), scored.map { it.id })
        assertNotEquals(original, scored)
    }

    @Test
    fun `rank empty input returns empty output`() {
        assertTrue(Operators.rank(emptyList(), now).isEmpty())
    }

    // ------------------------------------------------------------------
    // present — progressive-disclosure summary format
    // ------------------------------------------------------------------

    /** Epoch used by every present case; matches the Python reference run. */
    private val mentionEpoch: Long = 1786000000L

    /** ISO string Python produces for [mentionEpoch] under TZ=Asia/Shanghai. */
    private val mentionIso: String = "2026-08-06T15:06:40"

    private fun sampleNode(
        hashId: String = "abcdef0123456789abcdef0123456789",
        content: String = "Meeting with Alice about Project X",
        nodeType: String = "event",
        baseType: String = "content",
        eventTime: String? = "2026-08-08",
        eventTimeRaw: String? = "2026-08-08",
        mentionTime: Long = mentionEpoch,
    ): Node = Node(
        hashId = hashId,
        baseType = baseType,
        nodeType = nodeType,
        content = content,
        mentionTime = mentionTime,
        eventTimeRaw = eventTimeRaw,
        eventTime = eventTime,
    )

    @Test
    fun `present short ASCII content produces full preview without truncation marker`() {
        // Python: present([node_short])[0] ==
        //   {"hash":"abcdef01","preview":"Meeting with Alice about Project X",
        //    "mention_time":"2026-08-06T15:06:40","entities":[],"node_type":"event",
        //    "event_time":"2026-08-08"}
        val node = sampleNode()
        val summary = Operators.present(listOf(node), zoneId = zone)[0]
        assertEquals("abcdef01", summary.hash)
        assertEquals("Meeting with Alice about Project X", summary.preview)
        assertEquals(mentionIso, summary.mentionTime)
        assertTrue(summary.entities.isEmpty())
        assertEquals("event", summary.nodeType)
        assertEquals("2026-08-08", summary.eventTime)
    }

    @Test
    fun `present long ASCII content truncates at 80 chars with plus marker`() {
        // Python: content (104 chars) -> preview == content[:80] + "[+]" (83 chars total).
        val content = "This is a very long meeting summary that definitely exceeds the eighty character preview limit for sure."
        assertEquals(104, content.length)
        val node = sampleNode(content = content, eventTime = null, eventTimeRaw = null)
        val summary = Operators.present(listOf(node), zoneId = zone)[0]
        val expectedPreview = content.take(80) + "[+]"
        assertEquals(expectedPreview, summary.preview)
        assertEquals(83, summary.preview.length)
        assertEquals("abcdef01", summary.hash)
        assertEquals(mentionIso, summary.mentionTime)
        assertEquals("event", summary.nodeType)
        assertNull(summary.eventTime)
    }

    @Test
    fun `present content of exactly 80 chars is not truncated`() {
        // Python: present 80 'A's -> preview has no [+].
        val content = "A".repeat(80)
        val node = sampleNode(content = content, eventTime = null, eventTimeRaw = null)
        val summary = Operators.present(listOf(node), zoneId = zone)[0]
        assertEquals(content, summary.preview)
        assertFalse(summary.preview.contains("[+]"))
    }

    @Test
    fun `present content of 81 chars truncates with plus marker`() {
        // Python: present 81 'A's -> preview == 80 'A's + "[+]".
        val content = "A".repeat(81)
        val node = sampleNode(content = content, eventTime = null, eventTimeRaw = null)
        val summary = Operators.present(listOf(node), zoneId = zone)[0]
        assertEquals("A".repeat(80) + "[+]", summary.preview)
    }

    @Test
    fun `present CJK content of 80 codepoints is not truncated`() {
        // Python: present 80 '会' -> preview length 80, no [+]. Truncation is by
        // codepoint count (Python len), not byte count.
        val content = "会".repeat(80)
        val node = sampleNode(
            hashId = "cjk80hash0123456789abcdef0123456789",
            content = content,
            eventTime = null,
            eventTimeRaw = null,
        )
        val summary = Operators.present(listOf(node), zoneId = zone)[0]
        assertEquals(80, summary.preview.length)
        assertEquals(content, summary.preview)
        assertFalse(summary.preview.contains("[+]"))
    }

    @Test
    fun `present CJK content of 81 codepoints truncates at 80 with plus marker`() {
        // Python: present 81 '会' -> preview == 80 '会' + "[+]".
        val content = "会".repeat(81)
        val node = sampleNode(
            hashId = "cjk81hash0123456789abcdef0123456789",
            content = content,
            eventTime = null,
            eventTimeRaw = null,
        )
        val summary = Operators.present(listOf(node), zoneId = zone)[0]
        assertEquals("会".repeat(80) + "[+]", summary.preview)
        assertEquals(83, summary.preview.length)
    }

    @Test
    fun `present short CJK content under 80 codepoints is shown in full`() {
        // Python: present cjk_long (55 codepoints) -> preview == full content, no [+].
        val content = "今天我和张三在咖啡馆讨论了关于新项目的详细规划，包括预算、时间线和人员分配等各个方面，会议持续了大约两个小时。"
        assertEquals(55, content.length)
        val node = sampleNode(
            hashId = "cjklonghash123456789abcdef0123456789",
            content = content,
            eventTime = "2026-08-13",
            eventTimeRaw = null,
        )
        val summary = Operators.present(listOf(node), zoneId = zone)[0]
        assertEquals("cjklongh", summary.hash)
        assertEquals(content, summary.preview)
        assertEquals(mentionIso, summary.mentionTime)
        assertEquals("event", summary.nodeType)
        assertEquals("2026-08-13", summary.eventTime)
    }

    @Test
    fun `present attaches entity names from the mapping when the hash is present`() {
        // Python: present([node], entity_names={hash: ["Bob","Alice"]}) ->
        //   entities == ["Bob","Alice"].
        val node = sampleNode(
            hashId = "entityhash123456789abcdef0123456789",
            content = "Lunch with Bob",
            eventTime = null,
            eventTimeRaw = null,
        )
        val names = mapOf("entityhash123456789abcdef0123456789" to listOf("Bob", "Alice"))
        val summary = Operators.present(listOf(node), entityNames = names, zoneId = zone)[0]
        assertEquals(listOf("Bob", "Alice"), summary.entities)
    }

    @Test
    fun `present yields empty entities when the hash is missing from the mapping`() {
        val node = sampleNode(
            hashId = "entityhash123456789abcdef0123456789",
            content = "Lunch with Bob",
            eventTime = null,
            eventTimeRaw = null,
        )
        val summary = Operators.present(listOf(node), entityNames = emptyMap(), zoneId = zone)[0]
        assertTrue(summary.entities.isEmpty())
    }

    @Test
    fun `present treats null entity names as an empty mapping`() {
        val node = sampleNode(
            hashId = "entityhash123456789abcdef0123456789",
            content = "Lunch with Bob",
            eventTime = null,
            eventTimeRaw = null,
        )
        val summary = Operators.present(listOf(node), entityNames = null, zoneId = zone)[0]
        assertTrue(summary.entities.isEmpty())
    }

    @Test
    fun `present entity node carries node_type entity`() {
        // Python: present entity_node -> node_type == "entity".
        val node = sampleNode(
            hashId = "entitynodehash123456789abcdef0123456",
            baseType = "entity",
            nodeType = "entity",
            content = "Alice: software engineer",
            eventTime = null,
            eventTimeRaw = null,
        )
        val summary = Operators.present(listOf(node), zoneId = zone)[0]
        assertEquals("entityno", summary.hash)
        assertEquals("Alice: software engineer", summary.preview)
        assertEquals("entity", summary.nodeType)
        assertNull(summary.eventTime)
    }

    @Test
    fun `present hash prefix is exactly 8 chars`() {
        val node = sampleNode(hashId = "entitynodehash123456789abcdef0123456")
        val summary = Operators.present(listOf(node), zoneId = zone)[0]
        assertEquals(8, summary.hash.length)
        assertEquals("entityno", summary.hash)
    }

    @Test
    fun `present preserves input order across multiple nodes`() {
        val a = sampleNode(hashId = "abcdef0123456789abcdef0123456789", content = "a")
        val b = sampleNode(hashId = "abcdef0123456789abcdef0123456789", content = "long" + "x".repeat(100))
        val c = sampleNode(
            hashId = "entitynodehash123456789abcdef0123456",
            baseType = "entity",
            nodeType = "entity",
            content = "c",
        )
        val summaries = Operators.present(listOf(a, b, c), zoneId = zone)
        assertEquals(listOf("abcdef01", "abcdef01", "entityno"), summaries.map { it.hash })
    }

    @Test
    fun `present mention_time is ISO 8601 at second precision with no offset`() {
        // Python: datetime.fromtimestamp(1786000000.0).isoformat(timespec="seconds")
        //       == "2026-08-06T15:06:40" under TZ=Asia/Shanghai (naive, no +08:00).
        val node = sampleNode()
        val summary = Operators.present(listOf(node), zoneId = zone)[0]
        assertEquals("2026-08-06T15:06:40", summary.mentionTime)
        // Naive format: no timezone offset suffix.
        assertFalse(summary.mentionTime.contains("+"))
        assertFalse(summary.mentionTime.contains("Z"))
    }

    @Test
    fun `present mention_time truncates sub-second fractions to seconds`() {
        // Python: datetime.fromtimestamp(1786000000.999).isoformat(timespec="seconds")
        //       == "2026-08-06T15:06:40" (fractional part dropped).
        // Kotlin Node.mentionTime is Long (whole seconds), so this just confirms
        // the epoch -> ISO mapping for the same whole-second epoch.
        val node = sampleNode(mentionTime = 1786000000L)
        val summary = Operators.present(listOf(node), zoneId = zone)[0]
        assertEquals("2026-08-06T15:06:40", summary.mentionTime)
    }

    @Test
    fun `present life_capture node carries node_type and null event_time`() {
        // Python: present life_capture node -> node_type == "life_capture", event_time == None.
        val node = sampleNode(
            hashId = "noet0hash123456789abcdef01234567890",
            nodeType = "life_capture",
            content = "photo",
            eventTime = null,
            eventTimeRaw = null,
        )
        val summary = Operators.present(listOf(node), zoneId = zone)[0]
        assertEquals("noet0has", summary.hash)
        assertEquals("photo", summary.preview)
        assertEquals("life_capture", summary.nodeType)
        assertNull(summary.eventTime)
    }

    // ------------------------------------------------------------------
    // Progressive-disclosure invariant: never leak full text or metadata
    // ------------------------------------------------------------------

    @Test
    fun `present never leaks the full content when it exceeds the preview length`() {
        // The whole point of progressive disclosure: a summary of a >80-char node
        // must not contain the full content string anywhere in its fields.
        val content = "This is a very long meeting summary that definitely exceeds the eighty character preview limit for sure."
        assertTrue("fixture must exceed preview length", content.length > Operators.PREVIEW_LENGTH)
        val node = sampleNode(content = content, eventTime = null, eventTimeRaw = null)
        val summary = Operators.present(listOf(node), zoneId = zone)[0]
        // The full content must not appear verbatim in any field of the summary.
        assertFalse(
            "full content leaked into summary: $summary",
            summary.preview == content ||
                summary.hash == content ||
                summary.mentionTime == content ||
                summary.entities.contains(content) ||
                summary.nodeType == content ||
                summary.eventTime == content,
        )
        // Specifically the preview must be the truncated form, not the full text.
        assertNotEquals(content, summary.preview)
        assertTrue(summary.preview.endsWith("[+]"))
        assertTrue(content.startsWith(summary.preview.dropLast(3)))
    }

    @Test
    fun `present summary has exactly the six progressive-disclosure fields`() {
        // Python: present output dict keys == {hash, preview, mention_time, entities, node_type, event_time}.
        val node = sampleNode()
        val summary = Operators.present(listOf(node), zoneId = zone)[0]
        val fields = RankItem::class.java // placeholder to keep imports honest
        // The data class component count is the structural contract.
        assertEquals(6, NodeSummary::class.java.declaredMethods.count {
            it.name.startsWith("get") && !it.name.startsWith("getClass")
        })
        // Sanity: the field names we expect are all present and accessible.
        assertEquals("abcdef01", summary.hash)
        assertTrue(summary.preview.isNotEmpty())
        assertTrue(summary.mentionTime.isNotEmpty())
        assertEquals("event", summary.nodeType)
        // entities / eventTime covered by dedicated tests above.
        @Suppress("UNUSED_VARIABLE")
        val unused = fields // keep the import meaningful for future field-count assertions
    }

    @Test
    fun `present empty node list returns empty summary list`() {
        assertTrue(Operators.present(emptyList(), zoneId = zone).isEmpty())
    }
}
