package com.l2dchat.core.mem

import java.time.ZoneId
import org.junit.Assert.assertEquals
import org.junit.Assert.assertFalse
import org.junit.Assert.assertTrue
import org.junit.Assert.fail
import org.junit.Test

/**
 * Cross-validated unit tests for [TimeParse.parseEventTime].
 *
 * Every epoch-second assertion below was generated by running the Python reference
 * `mem/timeparse.py::parse_event_time` under `TZ=Asia/Shanghai` and recording the
 * exact `(start_ts, end_ts, approx)` tuple. The Kotlin side passes
 * [ZoneId.of]`("Asia/Shanghai")` explicitly so the suite is timezone-independent
 * and reproduces the Python output bit-for-bit.
 *
 * Reference generation command (run 2026-08-13):
 * ```
 * TZ=Asia/Shanghai python3 -c "from mem.timeparse import parse_event_time as p; \
 *   print(p('2025'))"   # -> (1735660800.0, 1767196800.0, False)
 * ```
 */
class TimeParseTest {

    private val zone = ZoneId.of("Asia/Shanghai")

    // ------------------------------------------------------------------
    // Point expressions — epoch seconds cross-validated against Python
    // (TZ=Asia/Shanghai, time.mktime).
    // ------------------------------------------------------------------

    @Test
    fun `year precision expands to whole year half-open interval`() {
        // Python: parse_event_time("2025") == (1735660800.0, 1767196800.0, False)
        val (start, end, approx) = TimeParse.parseEventTime("2025", zone)
        assertEquals(1735660800L, start)
        assertEquals(1767196800L, end)
        assertFalse(approx)
    }

    @Test
    fun `month precision expands to whole month half-open interval`() {
        // Python: parse_event_time("2026-03") == (1772294400.0, 1774972800.0, False)
        val (start, end, approx) = TimeParse.parseEventTime("2026-03", zone)
        assertEquals(1772294400L, start)
        assertEquals(1774972800L, end)
        assertFalse(approx)
    }

    @Test
    fun `day precision expands to single day half-open interval`() {
        // Python: parse_event_time("2026-08-08") == (1786118400.0, 1786204800.0, False)
        val (start, end, approx) = TimeParse.parseEventTime("2026-08-08", zone)
        assertEquals(1786118400L, start)
        assertEquals(1786204800L, end)
        assertFalse(approx)
    }

    @Test
    fun `minute precision expands to single minute half-open interval`() {
        // Python: parse_event_time("2026-08-08T15:00") == (1786172400.0, 1786172460.0, False)
        val (start, end, approx) = TimeParse.parseEventTime("2026-08-08T15:00", zone)
        assertEquals(1786172400L, start)
        assertEquals(1786172460L, end)
        assertFalse(approx)
    }

    // ------------------------------------------------------------------
    // Interval forms
    // ------------------------------------------------------------------

    @Test
    fun `closed interval expands end day inclusively into half-open`() {
        // Python: parse_event_time("2026-07-31/2026-08-02")
        //       == (1785427200.0, 1785686400.0, False)
        // End is day-precision 2026-08-02 advanced by +1 day -> 2026-08-03 00:00.
        val (start, end, approx) = TimeParse.parseEventTime("2026-07-31/2026-08-02", zone)
        assertEquals(1785427200L, start)
        assertEquals(1785686400L, end)
        assertFalse(approx)
    }

    @Test
    fun `open-ended interval A_slash_dotdot yields Long MAX_VALUE end`() {
        // Python: parse_event_time("2025-12/..") == (1764518400.0, inf, False)
        // Kotlin represents float("inf") as Long.MAX_VALUE (see TimeParse kdoc).
        val (start, end, approx) = TimeParse.parseEventTime("2025-12/..", zone)
        assertEquals(1764518400L, start)
        assertEquals(Long.MAX_VALUE, end)
        assertFalse(approx)
    }

    @Test
    fun `approximate flag til sets approx true and still expands interval`() {
        // Python: parse_event_time("2026-03~") == (1772294400.0, 1774972800.0, True)
        val (start, end, approx) = TimeParse.parseEventTime("2026-03~", zone)
        assertEquals(1772294400L, start)
        assertEquals(1774972800L, end)
        assertTrue(approx)
    }

    @Test
    fun `approximate flag works on day precision too`() {
        // Python: parse_event_time("2026-08-08~") == (1786118400.0, 1786204800.0, True)
        val (start, end, approx) = TimeParse.parseEventTime("2026-08-08~", zone)
        assertEquals(1786118400L, start)
        assertEquals(1786204800L, end)
        assertTrue(approx)
    }

    @Test
    fun `leading and trailing whitespace is stripped before parsing`() {
        // Python: parse_event_time("  2026-08-08  ") == (1786118400.0, 1786204800.0, False)
        val (start, end, approx) = TimeParse.parseEventTime("  2026-08-08  ", zone)
        assertEquals(1786118400L, start)
        assertEquals(1786204800L, end)
        assertFalse(approx)
    }

    // ------------------------------------------------------------------
    // Precision-advancement edge cases (month/year rollover)
    // ------------------------------------------------------------------

    @Test
    fun `december month precision rolls over into january of next year`() {
        // Python: parse_event_time("2025-12") == (1764518400.0, 1767196800.0, False)
        // Verified live: start 2025-12-01 00:00 CST, end 2026-01-01 00:00 CST.
        val (start, end, approx) = TimeParse.parseEventTime("2025-12", zone)
        assertEquals(1764518400L, start)
        assertEquals(1767196800L, end)
        assertFalse(approx)
    }

    // ------------------------------------------------------------------
    // Error cases — all must throw ToolValidationError
    // ------------------------------------------------------------------

    @Test
    fun `empty string throws ToolValidationError`() {
        try {
            TimeParse.parseEventTime("", zone)
            fail("expected ToolValidationError for empty string")
        } catch (e: ToolValidationError) {
            assertTrue(e.message!!.contains("non-empty string"))
        }
    }

    @Test
    fun `blank-only string throws ToolValidationError`() {
        try {
            TimeParse.parseEventTime("   ", zone)
            fail("expected ToolValidationError for blank string")
        } catch (e: ToolValidationError) {
            assertTrue(e.message!!.contains("non-empty string"))
        }
    }

    @Test
    fun `garbage input throws ToolValidationError`() {
        try {
            TimeParse.parseEventTime("garbage", zone)
            fail("expected ToolValidationError for garbage input")
        } catch (e: ToolValidationError) {
            assertTrue(e.message!!.contains("invalid time point"))
        }
    }

    @Test
    fun `invalid month 13 throws ToolValidationError`() {
        try {
            TimeParse.parseEventTime("2026-13", zone)
            fail("expected ToolValidationError for month 13")
        } catch (e: ToolValidationError) {
            assertTrue(e.message!!.contains("invalid calendar date"))
        }
    }

    @Test
    fun `invalid day 32 throws ToolValidationError`() {
        try {
            TimeParse.parseEventTime("2026-08-32", zone)
            fail("expected ToolValidationError for day 32")
        } catch (e: ToolValidationError) {
            assertTrue(e.message!!.contains("invalid calendar date"))
        }
    }

    @Test
    fun `invalid hour 25 throws ToolValidationError`() {
        try {
            TimeParse.parseEventTime("2026-08-08T25:00", zone)
            fail("expected ToolValidationError for hour 25")
        } catch (e: ToolValidationError) {
            assertTrue(e.message!!.contains("invalid calendar date"))
        }
    }

    @Test
    fun `reversed interval throws ToolValidationError`() {
        // Python: parse_event_time("2026-08/2026-07") raises ToolValidationError
        // ("interval end is not after its start").
        try {
            TimeParse.parseEventTime("2026-08/2026-07", zone)
            fail("expected ToolValidationError for reversed interval")
        } catch (e: ToolValidationError) {
            assertTrue(e.message!!.contains("not after its start"))
        }
    }

    @Test
    fun `open-ended interval never trips the reversed check`() {
        // A/.. has endTs = Long.MAX_VALUE which must bypass the endTs <= startTs guard.
        // Should not throw.
        val (start, end, approx) = TimeParse.parseEventTime("2020-01/..", zone)
        assertEquals(Long.MAX_VALUE, end)
        assertTrue(end > start)
        assertFalse(approx)
    }
}
