"""
Permission utilities package.

Re-exports the public API from submodules for convenient access.
"""

from ...types.permissions import (
    AsyncAgentDecisionReason,
    HookDecisionReason,
    ModeDecisionReason,
    OtherDecisionReason,
    PermissionAllowDecision,
    PermissionAskDecision,
    PermissionDecisionReason,
    PermissionDenyDecision,
    PermissionPassthrough,
    PermissionResult,
    PermissionRule,
    PermissionRuleSource,
    PermissionRuleValue,
    RuleDecisionReason,
    SafetyCheckDecisionReason,
    ToolPermissionContext,
    WorkingDirDecisionReason,
)
from .filesystem import (
    DANGEROUS_DIRECTORIES,
    DANGEROUS_FILES,
    FILE_EDIT_TOOL_NAME,
    FILE_READ_TOOL_NAME,
    SafetyCheckResult,
    check_path_safety_for_auto_edit,
    check_read_permission_for_tool,
    check_write_permission_for_tool,
    get_allow_rules,
    get_ask_rules,
    get_deny_rules,
    is_dangerous_file_path_to_auto_edit,
    matching_rule_for_input,
    normalize_case_for_comparison,
    path_in_allowed_working_path,
)
from .path_validation import (
    expand_tilde,
    is_dangerous_removal_path,
)
from .approval import (
    AUTO_REJECT_REASON,
    ApprovalAllowState,
    ApprovalContractError,
    ApprovalDeferState,
    ApprovalDenyState,
    deny_for_unavailable_prompts,
    normalize_approval_state,
    resolve_approval_state,
    validate_approval_contract,
)
from .permission_rule_parser import (
    permission_rule_value_to_string,
)
from .denial_tracking import (
    DENIAL_LIMITS,
    build_denial_tracking_signature,
    normalize_denial_tracking_state,
    record_permission_denial,
    reset_denial_tracking_state,
    should_fallback_to_interactive_prompt,
)
from .permissions import (
    create_permission_request_message,
    get_ask_rule_for_tool,
    get_deny_rule_for_tool,
    has_permissions_to_use_tool,
    tool_always_allowed_rule,
)

__all__ = [
    # Types
    "ModeDecisionReason",
    "OtherDecisionReason",
    "HookDecisionReason",
    "AsyncAgentDecisionReason",
    "PermissionAllowDecision",
    "PermissionAskDecision",
    "PermissionDecisionReason",
    "PermissionDenyDecision",
    "PermissionPassthrough",
    "PermissionResult",
    "PermissionRule",
    "PermissionRuleSource",
    "PermissionRuleValue",
    "RuleDecisionReason",
    "SafetyCheckDecisionReason",
    "ToolPermissionContext",
    "WorkingDirDecisionReason",
    # Filesystem
    "DANGEROUS_DIRECTORIES",
    "DANGEROUS_FILES",
    "FILE_EDIT_TOOL_NAME",
    "FILE_READ_TOOL_NAME",
    "SafetyCheckResult",
    "check_path_safety_for_auto_edit",
    "check_read_permission_for_tool",
    "check_write_permission_for_tool",
    "get_allow_rules",
    "get_ask_rules",
    "get_deny_rules",
    "is_dangerous_file_path_to_auto_edit",
    "matching_rule_for_input",
    "normalize_case_for_comparison",
    "path_in_allowed_working_path",
    "expand_tilde",
    "is_dangerous_removal_path",
    "AUTO_REJECT_REASON",
    "ApprovalAllowState",
    "ApprovalContractError",
    "ApprovalDeferState",
    "ApprovalDenyState",
    "deny_for_unavailable_prompts",
    "normalize_approval_state",
    "resolve_approval_state",
    "validate_approval_contract",
    "permission_rule_value_to_string",
    "DENIAL_LIMITS",
    "build_denial_tracking_signature",
    "normalize_denial_tracking_state",
    "record_permission_denial",
    "reset_denial_tracking_state",
    "should_fallback_to_interactive_prompt",
    "create_permission_request_message",
    "get_ask_rule_for_tool",
    "get_deny_rule_for_tool",
    "has_permissions_to_use_tool",
    "tool_always_allowed_rule",
]
