"""Tool registration, gating, and surface exposure.

Python port of src/tools.ts tool-surface slice.
Scope: exposure only — no execution, TUI, skill/plugin loading, or command registry.
"""

from .registry import (
    BUILTIN_TOOL_REGISTRY,
    GATE_ALWAYS,
    GATE_BUILD_USER_TYPE,
    GATE_ENV_VAR,
    GATE_FEATURE_FLAG,
    GATE_PLATFORM,
    GATE_RUNTIME_CHECK,
    GATE_TEST_ENV,
    EXPOSURE_ANT_ONLY,
    EXPOSURE_LINUX_DEFERRED,
    EXPOSURE_LINUX_REQUIRED,
    EXPOSURE_PLATFORM_SPECIFIC,
    EXPOSURE_TEST_ONLY,
    INTERNAL_ONLY_TOOLS,
    LINUX_DEFERRED_TOOLS,
    LINUX_REQUIRED_TOOLS,
    SOURCE_MODULE_INDEX,
    TOOL_ALIASES,
    TOOL_GATE_EXPRESSIONS,
    SchemaField,
    ToolDefinition,
    ToolSchema,
    classify_tool,
    find_tool_by_name,
    find_tool_by_source_module,
    get_all_source_module_names,
    get_all_tool_names,
    get_linux_deferred_names,
    get_linux_deferred_tools,
    get_linux_required_names,
    get_linux_required_tools,
    get_registered_aliases,
    get_tools_by_exposure,
    get_tools_by_gate,
    has_tool,
    is_internal_only,
    tool_matches_name,
)

__all__ = [
    "BUILTIN_TOOL_REGISTRY",
    "GATE_ALWAYS",
    "GATE_BUILD_USER_TYPE",
    "GATE_ENV_VAR",
    "GATE_FEATURE_FLAG",
    "GATE_PLATFORM",
    "GATE_RUNTIME_CHECK",
    "GATE_TEST_ENV",
    "EXPOSURE_ANT_ONLY",
    "EXPOSURE_LINUX_DEFERRED",
    "EXPOSURE_LINUX_REQUIRED",
    "EXPOSURE_PLATFORM_SPECIFIC",
    "EXPOSURE_TEST_ONLY",
    "INTERNAL_ONLY_TOOLS",
    "LINUX_DEFERRED_TOOLS",
    "LINUX_REQUIRED_TOOLS",
    "SOURCE_MODULE_INDEX",
    "TOOL_ALIASES",
    "TOOL_GATE_EXPRESSIONS",
    "SchemaField",
    "ToolDefinition",
    "ToolSchema",
    "classify_tool",
    "find_tool_by_name",
    "find_tool_by_source_module",
    "get_all_source_module_names",
    "get_all_tool_names",
    "get_linux_deferred_names",
    "get_linux_deferred_tools",
    "get_linux_required_names",
    "get_linux_required_tools",
    "get_registered_aliases",
    "get_tools_by_exposure",
    "get_tools_by_gate",
    "has_tool",
    "is_internal_only",
    "tool_matches_name",
]
